spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 101.42.250.83
    password: 123456
    port: 6379
shiro:
  loginUrl: /login.html
  unauthorizedUrl: /401.html   # 针对过滤器链生效，针对注解是不生效的

