spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234

shiro:
  loginUrl: /login.html
  unauthorizedUrl: /401.html   # 针对过滤器链生效，针对注解是不生效的
